name: mcMMOClassicQuests
version: 1.0
description: Quests module for mcMMO Classic
author: Browsit
website: https://github.com/Browsit/mcMMOClassicQuestsModule

main: org.browsit.mcmmoclassicquests.mcMMOClassicModule
depend: [mcMMO, Quests]